### PR TITLE
Adds a firebase store

### PR DESCRIPTION
**Pull request by brkattk**

### CODE REVIEW

**Comment by brkattk** [comment]
__Re: searchableTypes__

Without this, the vimeo sync provider is expecting that some observer on the oddcast bus is able to handle `{role: 'store', cmd: 'index'}`. This may not be true and we should default to not doing this.

**Comment by pmcconnell** [comment]
Does this need to be in this repo? Thought we were putting some of theses services in their own repos?

**Comment by blainsmith** [comment]
I am open to a new idea on how to ensure types are indexed for searching. Maybe the sync services expose an options to have types indexed or not and they use the proper patterns? It was opinionated of me to assume that when I wrote the Vimeo sync.

**Comment by blainsmith** [comment]
Also we could break these services out in the future, but for now that can live in the main one to its easier for all to run. Less dependancies, less releases to npm, until it becomes too much.

**Comment by brkattk** [comment]
Ensuring resources are indexed depends on whether you need a search function. Currently the only store that has the index command is `redis-search`. I think this is a good problem because its making us think about how a store should act

**Pull request closed without merging**
