### PR TITLE
Nasa data

### PR DESCRIPTION
**Pull request by pmcconnell**
have a look before I plug on with another data set for apple SDK testing

### CODE REVIEW

**Comment by blainsmith** [comment]
Sweet. Now you can add DATA_DIR to the package.json test scripts so they will pass.

**Comment by pmcconnell** [comment]
which config it travis hitting? Only test? do I need to config tape for ./test/data?

**Comment by blainsmith** [comment]
In **package.json**

```json
"test": "NODE_ENV=test DATA_DIR=./test/data npm run lint && npm run tape",
"tape": "NODE_ENV=test DATA_DIR=./test/data tape 'test/**/*_test.js' | tap-spec",
```

should do it...

**Comment by blainsmith** [comment]
This breaks local dev/testing. Should update. `.env.sample` to accommodate these changes.

**Comment by pmcconnell** [comment]
how are you testing that its broken? I'm all green right now?

**Comment by blainsmith** [comment]
`DATA_DIR` is not set in my local `.env` so it defaults to `./data` which doesn't actually contain the seed file.

**Comment by blainsmith** [comment]
Works for me locally now. I just get the memory issue you mentioned before with loading all of those videos.

**Comment by pmcconnell** [comment]
are you running npm run nasa?

**Comment by blainsmith** [comment]
No I didn't know that command existed, I just ran npm run dev as I've always been doing. We may be getting into config hell now haha.

**Comment by pmcconnell** [comment]
run dev is loading the nasa data? or you set data_dir to nasa?

**Comment by blainsmith** [comment]
The later, I can set DATA_DIR to whatever so I set to NASA for my own use and it hit a memory limit.

**Comment by pmcconnell** [comment]
I thought of adding 2gb, 3gb, etc configs. Not really sure how to deal with this automatically

**Comment by blainsmith** [comment]
What's your goal here with the NASA data? Should this be the default set of data from a fresh clone of Oddworks and running locally to run in memory?

**Comment by pmcconnell** [comment]
Dunno. For now its the best set of data we have. Its not great but I guess its better than the current minimal test data set.

If we were to make this the default dev set, the next hurdle would be getting nodemon to work with the command line option to increase memory limits. I wasn't able to get it working with my brief look.

**Comment by blainsmith** [comment]
Ok I am fine with making it the default as long as that is the expected result and it works like the documentation said. I can take look to get this working like that.

**Comment by pmcconnell** [comment]
If you want to look at the nodemon issue thats cool.

**Comment by blainsmith** [comment]
I would even go as far as trimming down the videos too since I would expect devs would like to edit and play with the test data to see how responses change? Maybe we don't need 84903284903249023842 videos and thus eliminating the need for increasing the memory limit?

How would you, an iOS dev, like this to work?

**Comment by pmcconnell** [comment]
That is certainly an option.

A decent set of data to work with the iOS/tvOS apps would have 6+ collections and 6+ videos per collection. If we pare it down to that point and it gets us under the memory limit that would be fine.

**Comment by blainsmith** [comment]
@barthdamon Care to chime in here?

**Comment by barthdamon** [comment]
I'm not seeing any views here:
https://github.com/oddnetworks/oddworks/pull/31/commits/0a657abfca8ef120ddecd551055d93349ddaee55
Are views hidden somewhere else?

I would add that for nasa we should definitely have a featuredMediaObject that is the nasa livestream.

**Comment by blainsmith** [comment]
@barthdamon https://github.com/oddnetworks/oddworks/tree/nasa_data/data/nasa/view

**Comment by blainsmith** [comment]
Cool, I can help work off this branch to trim down the videos. Also all these JSON files need to be de-JSON API-ified since the server will do it already.

* remove "links"
* remove "attributes" and move the sub-properties up to the root level
* rename "organization" to "channel"

**Comment by pmcconnell** [comment]
yeah it was a straight dump of the 1.0 beta server. If you want to update the script to dump it again I can forward that to you

**Comment by blainsmith** [comment]
Sure. Maybe make a public repo of it? 👍

**Comment by pmcconnell** [comment]
https://github.com/oddnetworks/odd-utilities

**Pull request merged**
