### PR TITLE
Fixing the Relationships endpoint response

### PR DESCRIPTION
**Pull request by aljachimiak**
This Should solve issue #210.

In this PR we:
- pass the correct data from the catalog-item-relationship-controller to the response-jsonapi
- fix the relationships tests to reflect the data change
- correct the output from the response-json-api
__Note: this is done with string detection on the original url.  It isn't optimal, but it solved the problem.  I'm open to suggestions on this part__ ([url to this commit)](https://github.com/oddnetworks/oddworks/commit/56bc531286abd67f90eb39f50bea8aceff836d66)

- add some tests for valid output from the relationships endpoint
- changing the tests for json-api-response cause a timing issue to rise to the surface in `admin-spec-list-controller-spec.js`.  So those were corrected too.

### CODE REVIEW

**Comment by blainsmith** [comment]
Had to push this out of band so I think they made it in and I will just close the issue.

**Comment by brkattk** [comment]
I am pretty sure these commits never made it in

**Comment by blainsmith** [comment]
We can reopen and verify that.

**Comment by blainsmith** [comment]
We can shut this up with

```json
"xo": {
    "esnext": true,
    "envs": [
      "node"
    ],
    "ignores": [
      "examples/**"
    ],
    "rules": {
      "object-property-newline": 0,
      "no-use-extend-native/no-use-extend-native": 0 // <--- ADD THIS??
    }
  },
```

**Pull request merged**
