### PR TITLE
Fixes for web channel

### PR DESCRIPTION
**Pull request by blainsmith**
Few things I noticed when working with the Odd Web Channel.

### CODE REVIEW

**Comment by kixxauth** [comment]
Derp, I did some work the same thing with the config/meta object merging (I'll stop committing to master now. dope). I had a slightly different approach that I *think* does the same thing:

https://github.com/oddnetworks/oddworks/blob/master/lib/services/identity/queries/index.js#L158-L181

Also, I have a TODO to put the string interpolation back into place. That was a nice feature.

https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/queries/index.js#L63-L75

The thing is that I thought it should belong in the catalog, but actually, that's wrong. It should go in identity, because config comes from identity.

**Comment by blainsmith** [comment]
Are we killing this branch then? I need the responses to those queries how I implemented them in order for web channel to work.

**Comment by kixxauth** [comment]
No, we can keep the logic:

This logic:

```js
		const omittedKeys = [
			'id',
			'type',
			'user',
			'channel',
			'platform',
			'updatedAt'
		];

		const meta = _.merge(
			{},
			_.omit(channel, omittedKeys),
			_.omit(platform, omittedKeys)
		);

		meta.user = args.user || null;
```

Does the same thing as this logic, but with moar readableness:

(_.merge() works recursively, so it merges the .features object too)

```js
		const config = {
			features: {},
			views: platform.views,
			user: args.user || null
		};

		const channelFeatures = _.keys(channel.features);
		const platformFeatures = _.keys(platform.features);
		const features = _.union(channelFeatures, platformFeatures);

		_.each(features, key => {
			const channelKey = _.get(channel, `features.${key}`);
			const platformKey = _.get(platform, `features.${key}`);
			const mergedKey = _.merge({}, channelKey, platformKey);

			_.set(config, `features.${key}`, mergedKey);
		});
```

**Comment by blainsmith** [comment]
:shipit:

**Pull request merged**
