### PR TITLE
Interpolate feature strings

### PR DESCRIPTION
**Pull request by blainsmith**
Just the usual hotness.

Grabs certain feature flags from identity and attaches them to the videos and does string interpolation on them as well.

### CODE REVIEW

**Comment by pmcconnell** [comment]
looks hawt

but (theres always a but) what if the meta features were configured in the data and not the server?

by this I mean what if the metaKeys were in the json? What if there were sections for different media types i.e. attach these values to videos, and these to promotions.

This also lends itself to being dashboard configurable.

Can certainly be added later as this is a great start.

**Comment by blainsmith** [comment]
Sure, right now these are special features flags for videos that the client has to know about and know what do do with them tho. So making this server configurable will require writing logic on the SDK to know what do do with the new flag, when added.

**Comment by pmcconnell** [comment]
put them in meta on the media objects but yes it needs more thought. 
Just trying to keep things generic as much as possible.

ship it

**Comment by blainsmith** [comment]
Cool. I'll get this merged and we can start a new issue around this enhancement.

**Pull request merged**
